services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "local"
      POSTGRES_USER: "local"
      POSTGRES_DB: "local"
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local" ]
      interval: 2s
      timeout: 5s
      retries: 10